services:
  mongo:
    image: mongo:6
    restart: always
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    expose:
      - "5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/bank_app
      - SECRET_KEY=supersecretkey
    depends_on:
      - mongo

  transactions:
    build: ./transactions
    expose:
      - "4000" # Make sure this matches the port your JS app uses
    environment:
      - MONGO_URI=mongodb://mongo:27017/bank_app
    depends_on:
      - backend

  frontend:
    build: ./studentportfolio
    expose:
      - "80"
    depends_on:
      - transactions

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend

volumes:
  mongo_data: